version: 0.0
os: linux
# hidding scripts for now
files:
  - source: /
    destination: /home/ubuntu/web/sites/altadis-codedeploy/
# permissions:
#    - object: /var/www/html
#      pattern: "**"
#      owner: apache
#      group: apache
#      mode: 755
#      type:
#        - file
hooks:
  BeforeInstall:
    - location: scripts/pre_deploy
      runas: ubuntu
    # - location: scripts/pre_deploy_1.sh
    #   runas: root
AfterInstall:
  - location: scripts/pos_deploy.sh
    runas: ubuntu
